deps install && lerna bootstrap after create project structure
rispa-io/rispa-cli pull request #12
Opened 2017-05-29 15:17 UTC by Fyzu

2017-05-29 15:18 UTC, Fyzu commented
![](https://github.trello.services/images/mini-trello-icon.png) [26 Подготавливать проект после установки плагинов к работе](https://trello.com/c/P7HjpKFq/26-26)

2017-05-29 17:49 UTC, Laiff requested changes

2017-05-29 17:49 UTC, Laiff commented on src/commands/createProject.js
> +    'npm',
Если тут устанавливать напрямую npm то корневой yarn.lock не будет создан, по хорошему нужно ориентироваться на npmClient поле в lerna.json указанный там или `npm`

2017-05-30 09:12 UTC, Laiff approved these changes

2017-05-30 09:51 UTC, merged