Implement install plugins as subtrees
rispa-io/rispa-cli pull request #17
Opened 2017-06-16 16:39 UTC by wuzyk

2017-06-17 17:15 UTC, Fyzu commented
Попытался добавить плагин, когда уже были изменения в проекте, в итоге под коммитом [Add plugins: rispa-client](http://s.csssr.ru/U5E1S7FNC/GitKraken_2017-06-17_19-57-22.png) ушли изменения в других плагинах и плагин не добавился.

Лог консоли:
 ```
 Install plugin with name: rispa-client
Working tree has modifications.  Cannot add.
[master 2463b76] Add plugins: rispa-client
 12 files changed, 301 insertions(+), 102 deletions(-)
 create mode 100644 packages/rispa-render-static/.eslintrc.js
 create mode 100644 packages/rispa-render-static/.rispa/activator.js
 create mode 100644 packages/rispa-render-static/.rispa/client.wpc.js
 create mode 100644 packages/rispa-render-static/package.json
 create mode 100644 packages/rispa-render-static/src/render.js
 create mode 100644 packages/rispa-render-static/yarn.lock
 rewrite packages/rispa-webpack/.rispa/activator.js (77%)
 delete mode 100644 packages/rispa-webpack/.rispa/babel-loader.js
 delete mode 100644 packages/rispa-webpack/.rispa/client.wpc.js
 delete mode 100644 packages/rispa-webpack/.rispa/common.wpc.js
 ```

Думаю стоит проверять, есть ли изменения в проекте и предлагать сделать коммит c этими изменениями, а потом запускать добавление.

2017-06-18 10:22 UTC, wuzyk commented
Согласен

2017-06-19 06:23 UTC, Laiff commented
![](https://github.trello.services/images/mini-trello-icon.png) [31 git subtree для плагинов](https://trello.com/c/xmBlcSXn/31-31-git-subtree-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%BE%D0%B2)

2017-06-19 06:53 UTC, Laiff requested changes

2017-06-19 06:53 UTC, Laiff commented on src/commands/updatePlugins.js
> +    handleError('No plugins to update')
Это не является ошибкой, это хороший проход просто мы ничего не обновили. Ошибка в данном кейсе быдет конфузить разработчика

2017-06-19 06:53 UTC, Laiff commented on src/commands/updatePlugins.js
>    process.exit(1)
Зачем тут `p.exit(1)`?

2017-06-19 06:56 UTC, wuzyk commented on src/commands/updatePlugins.js
>    process.exit(1)
Я не в курсе. Тоже хотел спросить об этом. Это делается в конце каждой команды

2017-06-19 06:57 UTC, Fyzu commented on src/commands/updatePlugins.js
>    process.exit(1)
Это старый код, такое завершение встречается практически в каждой команде, но оно бесполезно

2017-06-19 07:02 UTC, Nitive commented on src/commands/updatePlugins.js
>    process.exit(1)
Есть даже issue #16

2017-06-19 07:03 UTC, wuzyk commented on src/commands/updatePlugins.js
>    process.exit(1)
На это завязаны все тесты. Если убрать во всех командах, нужно будет переписать и все тесты. Делать это в этом PR?

2017-06-19 07:04 UTC, Fyzu commented on src/commands/updatePlugins.js
>    process.exit(1)
Мне кажется лучше в след. задаче, там много переделать нужно будет.

2017-06-19 07:04 UTC, Laiff commented on src/commands/updatePlugins.js
>    process.exit(1)
Нет это отдельной задачей, тогда сделаем

2017-06-19 07:23 UTC, Laiff approved these changes

2017-06-19 07:24 UTC, merged