Task-based architecture, improve commands
rispa-io/rispa-cli pull request #19
Opened 2017-06-20 06:30 UTC by Fyzu

2017-06-20 07:02 UTC, wuzyk commented on src/commands/createProject2.js
> +      bootstrapProjectDeps,
Не хватает сохранения конфигурации или оно переехало куда-то?

2017-06-20 07:04 UTC, Fyzu commented on src/commands/createProject2.js
> +      bootstrapProjectDeps,
Действительно не хватает

2017-06-20 08:07 UTC, Laiff requested changes

2017-06-20 08:07 UTC, Laiff commented on src/utils/pluginsCache.js
> +
Тут еще не доделано получается?

2017-06-21 19:46 UTC, Laiff requested changes

2017-06-21 19:46 UTC, Laiff commented on src/tasks/updatePlugin.js
> +const createRemovePlugin = name => improveTask({
Имя фабрики осталось от копипасты

2017-06-21 19:46 UTC, Laiff commented on src/utils/useYarn.js
> +const checkUseYarn = projectPath => fs.existsSync(path.resolve(projectPath, './yarn.lock'))
Давай все константы такго рода соберем в одном месте и будем везде использовать именно их, если что поменяеть придумаем будет проще все это отслеживать и модифицировать

2017-06-21 19:46 UTC, Laiff commented on src/commands/generate2.js
> +      .filter((generatorsPath, idx, values) => values.indexOf(generatorsPath) === idx)
Для чего эта фильтрация? Может ее сделать проще, а то сейчас квадрат проходов по массиву получается в виду indexOf

2017-06-25 10:54 UTC, Fyzu commented
![](https://github.trello.services/images/mini-trello-icon.png) [39 Улучшение информативности вывода команд cli](https://trello.com/c/Zjjztj0O/39-39-%D1%83%D0%BB%D1%83%D1%87%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4%D0%B0-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4-cli)

2017-06-26 07:37 UTC, Laiff approved these changes
Nice work!

2017-06-26 07:39 UTC, merged