Поддержка npm и выделение команд для запуска
rispa-io/rispa-cli pull request #2
Opened 2017-05-22 14:37 UTC by Fyzu

2017-05-22 14:58 UTC, Fyzu commented
![](https://github.trello.services/images/mini-trello-icon.png) [13. Вынести в отдельный пакет cli приложение](https://trello.com/c/8ugpMply/13-13-cli)

2017-05-23 06:51 UTC, Laiff requested changes

2017-05-23 06:51 UTC, Laiff commented on bin/ris.js
>  const useYarn = fs.existsSync('./yarn.lock')
Тут можно использовать сразу константу `USE_YARN` так как в рамках одного запуска скрипта это не изменится, и тогда не нужно будет прокидывать этот флаг через всю цепочку

2017-05-23 06:51 UTC, Laiff commented on bin/ris.js
> +  function selectPackage(packages) {
Функции которые не нуждаются в области видимости родителя должны быть вынесены в область видимости пакета

2017-05-23 06:51 UTC, Laiff commented on bin/ris.js
> +function findPackagesByPathFromCache(path, cache) {
Скрипт уже достаточно сильно разросся функционально, лучше его разделить на несколько скриптов и сложить в `$package/src/module.js`

2017-05-23 08:20 UTC, Laiff approved these changes

2017-05-23 08:33 UTC, merged