Implement `ris assemble` command
rispa-io/rispa-cli pull request #31
Opened 2017-06-26 12:41 UTC by wuzyk

2017-06-26 12:42 UTC, wuzyk commented
![](https://github.trello.services/images/mini-trello-icon.png) [37 `ris assemble` - Сборка проекта на основании rispa.json](https://trello.com/c/i3j1wy7R/37-37-ris-assemble-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B0-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D0%BD%D0%B0-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8-rispajson)

2017-06-26 12:57 UTC, Fyzu commented on src/commands/assemble.js
> +      {
Возможно тут нужна проверка на изменения в проекте (см. tasks/gitCheckChanges), т.к. subtree не даст добавить remote, пока есть изменения.

2017-06-26 12:57 UTC, Fyzu commented on src/commands/assemble.js
> +      },
Скорее всего как и с командами add & remove - тут стоит добавить коммит о том, какие плагины восстановлены.

2017-06-26 12:57 UTC, Fyzu commented on src/tasks/restorePlugin.js
> +    const { mode, remotes } = configuration
Я бы получение mode заменил на такой вариант:
```js
const mode = ctx.mode || ctx.configuration.mode
```
Что бы у пользователя была возможность форснуть девелоперский режим:
```sh
ris assemble --mode=dev
```

2017-06-26 12:57 UTC, Fyzu commented on src/commands/__tests__/assemble.test.js
> +      }).then(result => {
В тестах можно использовать async\await для лучшей читаемости

2017-06-26 13:17 UTC, wuzyk commented on src/tasks/restorePlugin.js
> +    const { mode, remotes } = configuration
Думаю, так делать не стоит. Потому что потому для удаления/обновления плагинов будет использоваться режим из конфигурации и будет больно. Если нужно сменить режим, то лучше поменять в rispa.json перед установкой

2017-06-26 13:25 UTC, wuzyk commented on src/commands/assemble.js
> +      },
В данном случае изменений не будет. В дев режиме изменения будут только в репах плагинов, но не в репе проекта. В прод режиме коммиты делаются самой командой subtree

2017-06-26 13:30 UTC, wuzyk commented on src/commands/assemble.js
> +      {
Можно конечно проверять, но на самом деле это лишнее. В дев режиме все равно есть ли изменения. В прод режиме сабтри просто ругнется на изменения, но ничего не сломается

2017-06-26 13:34 UTC, Fyzu commented on src/commands/assemble.js
> +      {
В Дев режиме можно скипнуть проверку, как сделано в addPlugins.
В прод режиме каждый не установленный плагин ругнется тем что ветка имеет изменения.

2017-06-27 07:01 UTC, Fyzu requested changes

2017-06-27 07:01 UTC, Fyzu commented on src/commands/assemble.js
> +      },
Нужно добавить удаление кэша плагинов, т.к. кэш может быть не актуальный после восстановления.
Смотри `tasks/cleanCache`.

2017-06-27 07:21 UTC, Fyzu approved these changes

2017-06-27 08:03 UTC, merged