Fix: cli should switch to local version properly
rispa-io/rispa-cli pull request #52
Opened 2017-07-06 11:34 UTC by berrunder

![](https://github.trello.services/images/mini-trello-icon.png) [cli should switch to local version propertly](https://trello.com/c/yX6CBY2f/78-cli-should-switch-to-local-version-propertly)
Изменил логику, чтобы проверялось нахождение запущенного скрипта в директории, куда устанавливаются глобальные модули. Для npm использовал пакет global-prefix, для yarn похожего не нашёл - сделал проверку на наличие в пути используемой yarn на всех платформах структуры папок `config/global/node_modules`.

2017-07-06 11:39 UTC, Fyzu requested changes
`if is installed as a plugin in the project`
How about this case?

2017-07-06 11:39 UTC, berrunder commented
Ещё сделал запуск самого локального скрипта, а не через ноду - на винде там лежит не js файл, а cmd-скрипт, поэтому локальный запуск фейлится.

2017-07-06 11:42 UTC, Laiff requested changes

2017-07-06 11:42 UTC, Laiff commented on bin/ris.js
> +const globalPrefix = require('global-prefix')
Глобальные и́мпорты в начало списка нужно располагать

2017-07-06 11:42 UTC, Laiff commented on bin/ris.js
> +    LOCAL_VERSION_PATH,
Первый аргумент пропал. Это законно?

2017-07-06 11:45 UTC, Laiff commented
On windows we can use bash and then cmd script will fail

2017-07-06 11:47 UTC, berrunder commented on bin/ris.js
> +    LOCAL_VERSION_PATH,
Я сделал запуск самого локального скрипта, а не через ноду - на винде там лежит не js файл, а cmd-скрипт, поэтому запуск через ноду вылетает с ошибкой. На unix-подобных платформах d LOCAL_VERSION_PATH js файл с правом на исполнение, поэтому тоже должно работать.

2017-07-06 12:42 UTC, Laiff commented
![](https://github.trello.services/images/mini-trello-icon.png) [cli should switch to local version propertly](https://trello.com/c/yX6CBY2f/78-cli-should-switch-to-local-version-propertly)

2017-07-06 13:59 UTC, berrunder commented
> On windows we can use bash and then cmd script will fail

Actually, LOCAL_VERSION_PATH points to file without extension. On windows, in local `node_modules/.bin` package installs two versions of `ris` executable - bash script `ris` and cmd script `ris.cmd`. Which of them executed is determined by current shell, i.e. cmd shell with execute `ris.cmd`, bash shell will execute `ris`. I checked both of this cases (cmd shell and git bash shell), they work correctly - bash script doesn't fail.

2017-07-06 14:04 UTC, Laiff commented
Ok. Looks good

2017-07-06 14:04 UTC, Laiff submitted a review, later dismissed

2017-07-06 16:22 UTC, berrunder commented
>> if is installed as a plugin in the project

> How about this case?

Implemented in 02b732e38d46e097f0176046a17944ce20639c67

2017-07-06 17:29 UTC, Fyzu requested changes
Switch to local version does not work on MacOs, if installed via yarn.

2017-07-06 17:43 UTC, Fyzu requested changes

2017-07-06 17:43 UTC, Fyzu commented on bin/ris.js
> +const runPluginVersion = args => {
Why 2 different functions, for the same action?

2017-07-07 08:02 UTC, Fyzu approved these changes

2017-07-07 09:19 UTC, Laiff approved these changes

2017-07-07 09:20 UTC, merged