Fix(crash): Crash on node 7
rispa-io/rispa-cli pull request #70
Opened 2017-07-25 16:39 UTC by Fyzu

2017-07-25 16:42 UTC, Fyzu commented
![](https://github.trello.services/images/mini-trello-icon.png) [113. Crash on node 7.10](https://trello.com/c/HBm9pBXf/113-113-crash-on-node-710)

2017-07-26 11:35 UTC, Laiff requested changes

2017-07-26 11:35 UTC, Laiff commented on .travis.yml
> +  - "7"
May be we should use build matrix for version now?

2017-08-10 07:07 UTC, Laiff commented
Resolved in #73

2017-08-10 07:07 UTC, closed without merging