run local cli version, if possible
rispa-io/rispa-cli pull request #9
Opened 2017-05-26 15:33 UTC by Fyzu

2017-05-26 15:34 UTC, Fyzu commented
![](https://github.trello.services/images/mini-trello-icon.png) [21. Детектировать исполнение cli из global и внутри проекта](https://trello.com/c/No4EvCVe/21-21-cli-global)

2017-05-26 15:49 UTC, Laiff requested changes

2017-05-26 15:49 UTC, Laiff commented on bin/ris.js
> +  return execPath.indexOf('/node_modules/.bin/') === -1 &&
На винде это повалится из-за разделителей пути, лучше собрать через делимитер из fs

2017-05-26 20:05 UTC, Laiff submitted a review, later dismissed

2017-05-28 09:29 UTC, Laiff requested changes

2017-05-28 09:29 UTC, Laiff commented on bin/ris.js
> +  const { dependencies, devDependencies } = requireIfExist(packageJsonPath) || {}
Пусть это будет дефолтное поведение функции `requireIfExist`

2017-05-28 11:07 UTC, Laiff approved these changes

2017-05-28 11:08 UTC, merged